filters:
  - threshold
  - RIQ
  - cluster

threshold:
  upper: 65
  lower: 0.1
  value_upper: NaN
  value_lower: 0

monotony:
  period_in_hours: 8
  allowed_value: Null
  min_number_of_invalid_window: 5
  min_repeated_data: 6

RIQ:
  lower: 2
  upper: 98

cluster:
  horizontal_dist_in_degree: 0.075
  vertical_parameter:
    mode: 'on'
    value: 100
  RIQ_parameter:
    mode: 'off'
    lower: 5
    upper: 95
  n_samples: 4
  min_estations_per_cluster: 5
  zscore_soft: 8
  zscore_hard: 4
