filters:
  - threshold
  - cluster
  - zscore

threshold:
  upper: 48.0
  lower: -18.0
  value_upper: NaN
  value_lower: NaN

monotony_sequence:
  period_in_hours: 8
  allowed_value: Null
  min_number_of_invalid_window: 3
  min_repeated_data: 5

RIQ:
  lower: 1
  upper: 99

aceleration:
  zscore: 4

zscore:
  threshold: 6

cluster:
  horizontal_dist_in_degree: 0.75
  vertical_parameter:
    mode: 'on'
    value: 150
  RIQ_parameter:
    mode: 'off'
    lower: 5
    upper: 95
  n_samples: 4
  min_estations_per_cluster: 5
  zscore_soft: 7
  zscore_hard: 3
