filters:
  - threshold
  - RIQ
  - cluster
  - monotony_sequence
  
threshold:
  upper: 99.5
  lower: 7
  value_upper: NaN
  value_lower: NaN

monotony_sequence:
  period_in_hours: 10
  allowed_value: Null
  min_number_of_invalid_window: 3
  min_repeated_data: 6

RIQ:
  lower: 5
  upper: 95

cluster:
  horizontal_dist_in_degree: 0.85
  vertical_parameter:
    mode: 'on'
    value: 200
  RIQ_parameter:
    mode: 'off'
    lower: 5
    upper: 95
  n_samples: 4
  min_estations_per_cluster: 5
  zscore_soft: 8
  zscore_hard: 4
