filters:
  - threshold
  - cluster

threshold:
  upper: 1096
  lower: 800
  value_upper: NaN
  value_lower: NaN

cluster:
  horizontal_dist_in_degree: 0.05
  vertical_parameter:
    mode: 'off'
    value: Null
  RIQ_parameter:
    mode: 'off'
    lower: 5
    upper: 95
  n_samples: 4
  min_estations_per_cluster: 5
  zscore_soft: 7
  zscore_hard: 4
