filters:
  - clear_sky
  - threshold
  - monotony
  - accumulated
  - cluster

threshold:
  upper: 150
  lower: 0.05
  value_upper: NaN
  value_lower: 0

monotony:
  period_in_hours: 12
  allowed_value: 0
  min_number_of_invalid_window: 4
  min_repeated_data: 5

accumulated:
  perc_true_condiction: 65

cluster:
  horizontal_dist_in_degree: 0.04
  vertical_parameter:
    mode: 'off'
    value: Null
  RIQ_parameter:
    mode: 'on'
    lower: 5
    upper: 95
  n_samples: 4
  min_estations_per_cluster: 6
  zscore_soft: 8
  zscore_hard: 4

clear_sky:
  buffer_distance_in_degree: 0.05
  threhold_precip_min: 0.01
  acmf_info: 
    path: '/data/observed/abi-l2-acmf/clear_sky_mask/{procdate:%Y/%j}/abi-l2-acmf_clear_sky_mask_{procdate:%Y%m%d%H}*.nc'
    cloud_flags: [3]
    varname: 'clear_sky_mask'
    lat_name: 'latitude'
    lon_name: 'longitude'
